Traceback (most recent call last):
  File "/home/me/.local/bin/metta", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/hyperon/metta.py", line 33, in main
    with open(args.file) as f: program = f.read()
FileNotFoundError: [Errno 2] No such file or directory: 'test-suite/performance/gpt2-like/corpus/tmpdata/done_.metta'
real 0.05
user 0.04
sys 0.00
