[()]
[(Error (assertEqual (jetta (new-jetta-space) "(+ 1 2)") 3) 
Expected: [3]
Got: [(Error (jetta (Error (new-jetta-space) Exception caught:
ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=9090): Max retries exceeded with url: /contexts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8793ba9000>: Failed to establish a new connection: [Errno 111] Connection refused'))

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/adapters.py(700): send
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/sessions.py(703): send
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/sessions.py(589): request
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/api.py(59): request
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/api.py(115): post
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/tests/python_compat/jetta/compile.py(125): jetta_space
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(461): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
) "(+ 1 2)") Exception caught:
AttributeError: 'ExpressionAtom' object has no attribute 'get_object'

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/tests/python_compat/jetta/compile.py(52): jetta_unwrap_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(469): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
)]
Missed results: 3
Excessive results: (Error (jetta (Error (new-jetta-space) Exception caught:
ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=9090): Max retries exceeded with url: /contexts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8793ba9000>: Failed to establish a new connection: [Errno 111] Connection refused'))

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/adapters.py(700): send
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/sessions.py(703): send
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/sessions.py(589): request
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/api.py(59): request
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/lib/python3.10/site-packages/requests/api.py(115): post
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/tests/python_compat/jetta/compile.py(125): jetta_space
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(461): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
) "(+ 1 2)") Exception caught:
AttributeError: 'ExpressionAtom' object has no attribute 'get_object'

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/tests/python_compat/jetta/compile.py(52): jetta_unwrap_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(469): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
))]
